In [2]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori

In [3]:
#방법 1
# import csv
 
# f = open('../data2/groceries.csv', 'r')
# rdr = csv.reader(f)
# k = []
# for l in rdr:
#     k.append(l)

In [4]:
#방법 2
# f=open('../data2/groceries.csv','r',encoding='utf-8')
# df2 = []
# lines = f.readlines()
# dataset = []
# for i in lines:
#     dataset.append(i.split(','))
# dataset

In [5]:
#방법 3
df = pd.read_csv('../data2/groceries.csv',sep='\t',header=None)
df

                                                      0
0     citrus fruit,semi-finished bread,margarine,rea...
1                          tropical fruit,yogurt,coffee
2                                            whole milk
3            pip fruit,yogurt,cream cheese,meat spreads
4     other vegetables,whole milk,condensed milk,lon...
...                                                 ...
9830  sausage,chicken,beef,hamburger meat,citrus fru...
9831                                  cooking chocolate
9832  chicken,citrus fruit,other vegetables,butter,y...
9833  semi-finished bread,bottled water,soda,bottled...
9834  chicken,tropical fruit,other vegetables,vinega...

[9835 rows x 1 columns]

In [6]:
dataset = []
for temp in df[0]:
    dataset.append(temp.split(','))

In [7]:
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary,columns=te.columns_)
df

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,True,False,False
9831,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9832,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
9833,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9834,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [8]:
frequent_itemsets = apriori(df, min_support=0.1, use_colnames=True)
frequent_itemsets

    support            itemsets
0  0.110524     (bottled water)
1  0.193493  (other vegetables)
2  0.183935        (rolls/buns)
3  0.108998   (root vegetables)
4  0.174377              (soda)
5  0.104931    (tropical fruit)
6  0.255516        (whole milk)
7  0.139502            (yogurt)

In [18]:
from mlxtend.frequent_patterns import association_rules

association_rules(frequent_itemsets, metric='lift', min_threshold= 1)

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction]
Index: []