In [38]:
import pandas as pd

df = pd.read_csv('data/노인보호구역 지정현황.csv')

In [39]:
df

      연번  자치구             시설명   위치   지정일  비고
0      1  종로구       종로노인종합복지관  이화동  2009
1      2  종로구  종로노인종합복지관 무악센터  무악동  2016
2      3  종로구        서울노인복지센터  경운동  2016
3      4  종로구            락희거리  낙원동  2017
4      5  종로구     종묘광장공원 동순라길  인의동  2018
..   ...  ...             ...  ...   ...  ..
158  159  강동구          성내천경로당  성내동  2014
159  160  강동구       성암장수마을요양원  성내동  2016
160  161  강동구       강동노인종합복지관  명일동  2018
161  162  강동구           쉼터경로당  천호동  2019
162  163  강동구         구립강암경로당  암사동  2020

[163 rows x 6 columns]

In [40]:
df.drop(['연번','비고'],axis=1,inplace=True)

In [41]:
df

     자치구             시설명   위치   지정일
0    종로구       종로노인종합복지관  이화동  2009
1    종로구  종로노인종합복지관 무악센터  무악동  2016
2    종로구        서울노인복지센터  경운동  2016
3    종로구            락희거리  낙원동  2017
4    종로구     종묘광장공원 동순라길  인의동  2018
..   ...             ...  ...   ...
158  강동구          성내천경로당  성내동  2014
159  강동구       성암장수마을요양원  성내동  2016
160  강동구       강동노인종합복지관  명일동  2018
161  강동구           쉼터경로당  천호동  2019
162  강동구         구립강암경로당  암사동  2020

[163 rows x 4 columns]

In [43]:
# df= df.groupby('지정일')['자치구'].count()
# df
df1 = df.groupby(['자치구','지정일'])['위치'].count()

In [44]:
df1

자치구  지정일
강남구  2008    1
     2010    1
     2011    1
     2013    2
     2014    4
            ..
중구   2017    1
     2019    5
중랑구  2008    1
     2010    1
     2015    1
Name: 위치, Length: 132, dtype: int64

In [26]:
df1.sort_values(inplace=True,ascending=False)
df1

자치구
강서구     13
강남구     12
송파구     11
은평구     10
관악구      9
서초구      9
강동구      8
중구       8
동작구      8
양천구      7
성북구      7
동대문      7
마포구      6
노원구      6
서대문구     5
성동구      5
광진구      5
종로구      5
금천구      4
영등포구     4
용산구      4
구로구      3
중랑구      3
도봉구      2
강북구      2
Name: 위치, dtype: int64

In [45]:
df2 = pd.DataFrame(df1)

In [46]:
df2

          위치
자치구 지정일
강남구 2008   1
    2010   1
    2011   1
    2013   2
    2014   4
...       ..
중구  2017   1
    2019   5
중랑구 2008   1
    2010   1
    2015   1

[132 rows x 1 columns]

In [31]:
df2.reset_index(inplace=True)

In [33]:
df2.columns = ['자치구','갯수']

In [34]:
df2

     자치구  갯수
0    강서구  13
1    강남구  12
2    송파구  11
3    은평구  10
4    관악구   9
5    서초구   9
6    강동구   8
7     중구   8
8    동작구   8
9    양천구   7
10   성북구   7
11   동대문   7
12   마포구   6
13   노원구   6
14  서대문구   5
15   성동구   5
16   광진구   5
17   종로구   5
18   금천구   4
19  영등포구   4
20   용산구   4
21   구로구   3
22   중랑구   3
23   도봉구   2
24   강북구   2

In [66]:
# s = []
# temp = 0
# for i in df['합계']:
#     temp += i
#     s.append(temp)
# s

[3, 20, 27, 38, 43, 48, 58, 68, 78, 100, 115, 134, 151, 163]

In [67]:
# df['합계'] = s

In [35]:
df2

     자치구  갯수
0    강서구  13
1    강남구  12
2    송파구  11
3    은평구  10
4    관악구   9
5    서초구   9
6    강동구   8
7     중구   8
8    동작구   8
9    양천구   7
10   성북구   7
11   동대문   7
12   마포구   6
13   노원구   6
14  서대문구   5
15   성동구   5
16   광진구   5
17   종로구   5
18   금천구   4
19  영등포구   4
20   용산구   4
21   구로구   3
22   중랑구   3
23   도봉구   2
24   강북구   2

In [36]:
df2.to_csv('data/sen_road2.txt')