In [15]:
import pandas as pd

df1 = pd.read_csv('data/2007~2011노인교통사고(서울).csv')
df2 = pd.read_csv('data/2012~2016노인교통사고(서울).csv')
df3 = pd.read_csv('data/2017~2020노인교통사고(서울).csv')

In [16]:
df2.drop('시군구',axis=1,inplace=True)
df3.drop('시군구',axis=1,inplace=True)

In [17]:
df = pd.concat([df1,df2,df3],axis=1)

In [18]:
df

,시군구,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,합계,2642,3100,3609,3528,3733,4197,4492,5009,5388,5219,5357,5761,5912,5056
1,종로구,108,101,122,139,148,144,143,140,168,173,192,191,184,147
2,중구,82,95,140,124,134,143,145,162,165,139,156,164,151,161
3,용산구,88,84,115,114,87,119,137,158,169,167,163,170,144,95
4,성동구,76,89,102,98,112,106,128,153,177,139,161,158,162,158
5,동대문구,150,164,205,211,204,248,271,287,361,357,313,327,315,289
6,성북구,116,186,177,175,184,182,203,235,275,248,285,228,262,214
7,도봉구,74,104,117,119,111,122,135,171,170,171,170,190,189,160
8,은평구,106,164,197,166,194,221,177,195,208,217,195,244,246,195
9,서대문구,93,106,138,121,136,131,179,156,180,173,166,203,211,137
10,마포구,91,125,132,138,141,147,191,181,203,198,208,191,192,148
11,강서구,119,130,155,173,172,184,212,240,234,240,231,210,276,232
12,구로구,92,118,144,127,147,168,145,213,220,207,203,242,230,201
13,영등포구,141,164,182,179,210,224,269,266,315,312,328,350,341,296
14,동작구,76,69,125,99,114,129,156,148,175,196,200,225,203,199
15,관악구,118,143,152,158,169,181,203,231,218,171,184,182,194,209
16,강남구,112,126,165,157,192,239,251,283,260,303,324,351,352,359
17,강동구,110,110,140,118,152,167,168,202,206,217,221,242,286,196
18,송파구,167,189,181,172,188,268,241,292,299,274,321,373,395,336
19,서초구,98,122,121,148,165,163,190,200,202,248,237,290,284,247
20,양천구,78,109,125,112,124,136,144,171,227,191,177,209,237,198
21,중랑구,173,152,161,193,163,217,230,204,240,213,250,254,276,242
22,노원구,118,139,159,155,158,181,179,212,206,228,212,245,297,244
23,광진구,102,112,117,117,109,140,130,166,167,113,146,133,128,102
24,강북구,105,120,136,128,121,137,174,198,224,216,200,246,217,161
25,금천구,49,79,101,87,98,100,91,145,119,108,114,143,140,130

In [20]:
df = df.T
df

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
시군구,합계,종로구,중구,용산구,성동구,동대문구,성북구,도봉구,은평구,서대문구,...,강남구,강동구,송파구,서초구,양천구,중랑구,노원구,광진구,강북구,금천구
2007,2642,108,82,88,76,150,116,74,106,93,...,112,110,167,98,78,173,118,102,105,49
2008,3100,101,95,84,89,164,186,104,164,106,...,126,110,189,122,109,152,139,112,120,79
2009,3609,122,140,115,102,205,177,117,197,138,...,165,140,181,121,125,161,159,117,136,101
2010,3528,139,124,114,98,211,175,119,166,121,...,157,118,172,148,112,193,155,117,128,87
2011,3733,148,134,87,112,204,184,111,194,136,...,192,152,188,165,124,163,158,109,121,98
2012,4197,144,143,119,106,248,182,122,221,131,...,239,167,268,163,136,217,181,140,137,100
2013,4492,143,145,137,128,271,203,135,177,179,...,251,168,241,190,144,230,179,130,174,91
2014,5009,140,162,158,153,287,235,171,195,156,...,283,202,292,200,171,204,212,166,198,145
2015,5388,168,165,169,177,361,275,170,208,180,...,260,206,299,202,227,240,206,167,224,119
2016,5219,173,139,167,139,357,248,171,217,173,...,303,217,274,248,191,213,228,113,216,108
2017,5357,192,156,163,161,313,285,170,195,166,...,324,221,321,237,177,250,212,146,200,114
2018,5761,191,164,170,158,327,228,190,244,203,...,351,242,373,290,209,254,245,133,246,143
2019,5912,184,151,144,162,315,262,189,246,211,...,352,286,395,284,237,276,297,128,217,140
2020,5056,147,161,95,158,289,214,160,195,137,...,359,196,336,247,198,242,244,102,161,130

In [22]:
df = df.rename(columns=df.iloc[0])
df

,합계,종로구,중구,용산구,성동구,동대문구,성북구,도봉구,은평구,서대문구,...,강남구,강동구,송파구,서초구,양천구,중랑구,노원구,광진구,강북구,금천구
시군구,합계,종로구,중구,용산구,성동구,동대문구,성북구,도봉구,은평구,서대문구,...,강남구,강동구,송파구,서초구,양천구,중랑구,노원구,광진구,강북구,금천구
2007,2642,108,82,88,76,150,116,74,106,93,...,112,110,167,98,78,173,118,102,105,49
2008,3100,101,95,84,89,164,186,104,164,106,...,126,110,189,122,109,152,139,112,120,79
2009,3609,122,140,115,102,205,177,117,197,138,...,165,140,181,121,125,161,159,117,136,101
2010,3528,139,124,114,98,211,175,119,166,121,...,157,118,172,148,112,193,155,117,128,87
2011,3733,148,134,87,112,204,184,111,194,136,...,192,152,188,165,124,163,158,109,121,98
2012,4197,144,143,119,106,248,182,122,221,131,...,239,167,268,163,136,217,181,140,137,100
2013,4492,143,145,137,128,271,203,135,177,179,...,251,168,241,190,144,230,179,130,174,91
2014,5009,140,162,158,153,287,235,171,195,156,...,283,202,292,200,171,204,212,166,198,145
2015,5388,168,165,169,177,361,275,170,208,180,...,260,206,299,202,227,240,206,167,224,119
2016,5219,173,139,167,139,357,248,171,217,173,...,303,217,274,248,191,213,228,113,216,108
2017,5357,192,156,163,161,313,285,170,195,166,...,324,221,321,237,177,250,212,146,200,114
2018,5761,191,164,170,158,327,228,190,244,203,...,351,242,373,290,209,254,245,133,246,143
2019,5912,184,151,144,162,315,262,189,246,211,...,352,286,395,284,237,276,297,128,217,140
2020,5056,147,161,95,158,289,214,160,195,137,...,359,196,336,247,198,242,244,102,161,130

In [24]:
df = df.drop(df.index[0])
df

,합계,종로구,중구,용산구,성동구,동대문구,성북구,도봉구,은평구,서대문구,...,강남구,강동구,송파구,서초구,양천구,중랑구,노원구,광진구,강북구,금천구
2007,2642,108,82,88,76,150,116,74,106,93,...,112,110,167,98,78,173,118,102,105,49
2008,3100,101,95,84,89,164,186,104,164,106,...,126,110,189,122,109,152,139,112,120,79
2009,3609,122,140,115,102,205,177,117,197,138,...,165,140,181,121,125,161,159,117,136,101
2010,3528,139,124,114,98,211,175,119,166,121,...,157,118,172,148,112,193,155,117,128,87
2011,3733,148,134,87,112,204,184,111,194,136,...,192,152,188,165,124,163,158,109,121,98
2012,4197,144,143,119,106,248,182,122,221,131,...,239,167,268,163,136,217,181,140,137,100
2013,4492,143,145,137,128,271,203,135,177,179,...,251,168,241,190,144,230,179,130,174,91
2014,5009,140,162,158,153,287,235,171,195,156,...,283,202,292,200,171,204,212,166,198,145
2015,5388,168,165,169,177,361,275,170,208,180,...,260,206,299,202,227,240,206,167,224,119
2016,5219,173,139,167,139,357,248,171,217,173,...,303,217,274,248,191,213,228,113,216,108
2017,5357,192,156,163,161,313,285,170,195,166,...,324,221,321,237,177,250,212,146,200,114
2018,5761,191,164,170,158,327,228,190,244,203,...,351,242,373,290,209,254,245,133,246,143
2019,5912,184,151,144,162,315,262,189,246,211,...,352,286,395,284,237,276,297,128,217,140
2020,5056,147,161,95,158,289,214,160,195,137,...,359,196,336,247,198,242,244,102,161,130

In [25]:
df.reset_index(inplace=True)
df

,index,합계,종로구,중구,용산구,성동구,동대문구,성북구,도봉구,은평구,...,강남구,강동구,송파구,서초구,양천구,중랑구,노원구,광진구,강북구,금천구
0,2007,2642,108,82,88,76,150,116,74,106,...,112,110,167,98,78,173,118,102,105,49
1,2008,3100,101,95,84,89,164,186,104,164,...,126,110,189,122,109,152,139,112,120,79
2,2009,3609,122,140,115,102,205,177,117,197,...,165,140,181,121,125,161,159,117,136,101
3,2010,3528,139,124,114,98,211,175,119,166,...,157,118,172,148,112,193,155,117,128,87
4,2011,3733,148,134,87,112,204,184,111,194,...,192,152,188,165,124,163,158,109,121,98
5,2012,4197,144,143,119,106,248,182,122,221,...,239,167,268,163,136,217,181,140,137,100
6,2013,4492,143,145,137,128,271,203,135,177,...,251,168,241,190,144,230,179,130,174,91
7,2014,5009,140,162,158,153,287,235,171,195,...,283,202,292,200,171,204,212,166,198,145
8,2015,5388,168,165,169,177,361,275,170,208,...,260,206,299,202,227,240,206,167,224,119
9,2016,5219,173,139,167,139,357,248,171,217,...,303,217,274,248,191,213,228,113,216,108
10,2017,5357,192,156,163,161,313,285,170,195,...,324,221,321,237,177,250,212,146,200,114
11,2018,5761,191,164,170,158,327,228,190,244,...,351,242,373,290,209,254,245,133,246,143
12,2019,5912,184,151,144,162,315,262,189,246,...,352,286,395,284,237,276,297,128,217,140
13,2020,5056,147,161,95,158,289,214,160,195,...,359,196,336,247,198,242,244,102,161,130

In [26]:
df.rename(columns={'index':'지정일'},inplace=True)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 27 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   지정일     14 non-null     object
 1   합계      14 non-null     object
 2   종로구     14 non-null     object
 3   중구      14 non-null     object
 4   용산구     14 non-null     object
 5   성동구     14 non-null     object
 6   동대문구    14 non-null     object
 7   성북구     14 non-null     object
 8   도봉구     14 non-null     object
 9   은평구     14 non-null     object
 10  서대문구    14 non-null     object
 11  마포구     14 non-null     object
 12  강서구     14 non-null     object
 13  구로구     14 non-null     object
 14  영등포구    14 non-null     object
 15  동작구     14 non-null     object
 16  관악구     14 non-null     object
 17  강남구     14 non-null     object
 18  강동구     14 non-null     object
 19  송파구     14 non-null     object
 20  서초구     14 non-null     object
 21  양천구     14 non-null     object
 22  중랑구     14 non-null     object
 23  노원구     14 non-null     object
 24  광진구     14 non-null     object
 25  강북구     14 non-null     object
 26  금천구     14 non-null     object
dtypes: object(27)
memory usage: 3.1+ KB

In [28]:
df = df.astype({'지정일':'int64'})

In [29]:
df

,지정일,합계,종로구,중구,용산구,성동구,동대문구,성북구,도봉구,은평구,...,강남구,강동구,송파구,서초구,양천구,중랑구,노원구,광진구,강북구,금천구
0,2007,2642,108,82,88,76,150,116,74,106,...,112,110,167,98,78,173,118,102,105,49
1,2008,3100,101,95,84,89,164,186,104,164,...,126,110,189,122,109,152,139,112,120,79
2,2009,3609,122,140,115,102,205,177,117,197,...,165,140,181,121,125,161,159,117,136,101
3,2010,3528,139,124,114,98,211,175,119,166,...,157,118,172,148,112,193,155,117,128,87
4,2011,3733,148,134,87,112,204,184,111,194,...,192,152,188,165,124,163,158,109,121,98
5,2012,4197,144,143,119,106,248,182,122,221,...,239,167,268,163,136,217,181,140,137,100
6,2013,4492,143,145,137,128,271,203,135,177,...,251,168,241,190,144,230,179,130,174,91
7,2014,5009,140,162,158,153,287,235,171,195,...,283,202,292,200,171,204,212,166,198,145
8,2015,5388,168,165,169,177,361,275,170,208,...,260,206,299,202,227,240,206,167,224,119
9,2016,5219,173,139,167,139,357,248,171,217,...,303,217,274,248,191,213,228,113,216,108
10,2017,5357,192,156,163,161,313,285,170,195,...,324,221,321,237,177,250,212,146,200,114
11,2018,5761,191,164,170,158,327,228,190,244,...,351,242,373,290,209,254,245,133,246,143
12,2019,5912,184,151,144,162,315,262,189,246,...,352,286,395,284,237,276,297,128,217,140
13,2020,5056,147,161,95,158,289,214,160,195,...,359,196,336,247,198,242,244,102,161,130

In [30]:
df.to_csv('data/sen_acc.txt')