In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./data3/air.csv')

In [3]:
df

,MONTH,DAY_OF_WEEK,DEP_DEL15,DISTANCE_GROUP,DEP_BLOCK,SEGMENT_NUMBER,CONCURRENT_FLIGHTS,NUMBER_OF_SEATS,CARRIER_NAME,AIRPORT_FLIGHTS_MONTH,...,PLANE_AGE,DEPARTING_AIRPORT,LATITUDE,LONGITUDE,PREVIOUS_AIRPORT,PRCP,SNOW,SNWD,TMAX,AWND
0,1,1,0,1,MORNING,1,49,66,Mesa Airlines Inc.,5021,...,17,Raleigh-Durham International,35.875,-78.782,NONE,0.46,0.0,0.0,67.0,5.37
1,1,1,0,3,EARLY_MORNING,1,8,128,American Airlines Inc.,5021,...,19,Raleigh-Durham International,35.875,-78.782,NONE,0.46,0.0,0.0,67.0,5.37
2,1,1,0,2,MORNING,1,49,99,American Airlines Inc.,5021,...,11,Raleigh-Durham International,35.875,-78.782,NONE,0.46,0.0,0.0,67.0,5.37
3,1,1,0,1,EARLY_MORNING,1,8,99,American Airlines Inc.,5021,...,11,Raleigh-Durham International,35.875,-78.782,NONE,0.46,0.0,0.0,67.0,5.37
4,1,1,0,3,MORNING,1,49,143,Southwest Airlines Co.,5021,...,8,Raleigh-Durham International,35.875,-78.782,NONE,0.46,0.0,0.0,67.0,5.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1402913,3,1,0,1,AFTERNOON,8,17,123,Hawaiian Airlines Inc.,1258,...,18,Keahole,19.739,-156.046,Honolulu International,0.00,0.0,0.0,83.0,8.72
1402914,3,1,0,1,AFTERNOON,9,17,123,Hawaiian Airlines Inc.,1258,...,18,Keahole,19.739,-156.046,Honolulu International,0.00,0.0,0.0,83.0,8.72
1402915,3,1,0,1,AFTERNOON,10,17,123,Hawaiian Airlines Inc.,1258,...,15,Keahole,19.739,-156.046,Kahului Airport,0.00,0.0,0.0,83.0,8.72
1402916,3,1,0,1,EVENING,12,6,123,Hawaiian Airlines Inc.,1258,...,18,Keahole,19.739,-156.046,Honolulu International,0.00,0.0,0.0,83.0,8.72
1402917,3,1,0,1,EVENING,12,6,123,Hawaiian Airlines Inc.,1258,...,15,Keahole,19.739,-156.046,Honolulu International,0.00,0.0,0.0,83.0,8.72

In [ ]:
#DEP_DEL15 = TARGET 15분 이상의 출발 지연의 이진수(1은 예)
#DISTANCE_GROUP = 출발 항공기로 비행할 거리 그룹
#SEGMENT_NUMBER = 이 꼬리 번호가 하루 동안 사용되는 세그먼트
#CONCURRENT_FLIGHTS	 = 동일한 출발 구역에서 공항에서 출발하는 동시 항공편
#AIRPORT_FLIGHTS_MONTH = 월간 Avg 공항 항공편